### ISSUE TITLE
font missing

### ISSUE THREAD

**Issue by darrencuk** [simonbugler/inkyphat#1]
Hi,

when I run the (excellent) code on my pi zero w with inkyphat I get the following error about a missing font.

**Traceback (most recent call last):
  File "info.py", line 158, in <module>
    font = ImageFont.truetype("/home/pi/Pimoroni/inkyphat/fonts/elec.ttf", 10)
  File "/usr/lib/python2.7/dist-packages/PIL/ImageFont.py", line 238, in truetype
    return FreeTypeFont(font, size, index, encoding)
  File "/usr/lib/python2.7/dist-packages/PIL/ImageFont.py", line 127, in __init__
    self.font = core.getfont(font, size, index, encoding)
IOError: cannot open resource**

I have tried all the usual to get the font but all the fonts I choose are unreadable.

Please can you help?

Thanks

**Comment by simonbugler** [comment]
https://www.dafont.com/electronic-highway-sign.font
